project:
  type: website
  preview:
    port: 4200
    browser: false
  execute-dir: project

author: Aleksander Bang-Larsen

lang: da

website:
  title: "Aleksanders netværksanalyser"
  favicon: .github/favicon_io/favicon.ico
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/aleksanderbl29/SocialNetwork
  repo-actions: [edit, source, issue]
  repo-link-target: _blank
  site-url: https://aleksanderbl.dk/SocialNetwork/
  open-graph: true
  # sidebar:
  #   contents: auto
  navbar:
    left:
      - index.qmd
      - href: https://github.com/aleksanderbl29/SocialNetwork
        text: Link til koden
      - href: license.qmd
        text: Licens
    right:
      - href: https://aleksanderbl.dk
        text: Min hjemmeside
    search: true

format:
  html:
    theme: united
    toc: true
    smooth-scroll: true
